name: lab01
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install nbconvert ipykernel
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - run: python -m nbconvert --to pdf --execute pint_and_boiling_point.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: pint_and_boiling_point.pdf

