name: lab01
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install nbconvert
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - run: python -m nbconvert --to pdf pint_and_boiling_point.ipynb

