name: lab01
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert
      - uses: actions/checkout@v2
      - run: python -m nbconvert --to pdf pint_and_boiling_point.ipynb

