# name: lab02
# on:
#   push:
#     branches:
#       - 'main'
#     # paths:
#     # - ./'labs/**'
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     name: Build Assignment 1 .PDF Artifact
#     steps:
#       - uses: actions/checkout@v4
#       - uses: awalsh128/cache-apt-pkgs-action@latest
#         with:
#           packages: pandoc
#           version: 1.0
#           execute_install_scripts: true
#       - run: sudo apt-get install inkscape texlive-xetex
#       - uses: actions/setup-python@v5
#         with:
#           python-version: '3.12'
#           cache: 'pip'
#           cache-dependency-path: ./requirements.txt
#       - run: pip install -r ./requirements.txt
#       - run: python -m nbconvert --to pdf --execute ./labs/hw_01.ipynb
#       - uses: actions/upload-artifact@v4
#         with:
#           path: ./labs/hw_01.pdf

name: lab02
on:
  push:
    branches:
      - 'main'

jobs:
  run:
    runs-on: ubuntu-latest
    name: Build Assignment 1 .PDF Artifact
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pandoc
          version: 1.0
          execute_install_scripts: true
      - run: sudo apt-get install -y texlive texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-plain-generic fonts-freefont-ttf lmodern
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: ./requirements.txt
      - run: pip install -r ./requirements.txt
      - run: python -m nbconvert --to pdf --execute ./labs/hw_01.ipynb --log-level=DEBUG
      - uses: actions/upload-artifact@v4
        with:
          path: ./labs/hw_01.pdf
